//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Views.AccountStrings", typeof(AccountStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar periodo.
        /// </summary>
        public static string BtnGenerarPeriodo {
            get {
                return ResourceManager.GetString("BtnGenerarPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar datos.
        /// </summary>
        public static string BtnVerificarDatos {
            get {
                return ResourceManager.GetString("BtnVerificarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignaturas  asociadas.
        /// </summary>
        public static string LabelAsignaturasGestor {
            get {
                return ResourceManager.GetString("LabelAsignaturasGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Asignatura.
        /// </summary>
        public static string LabelIdAsignatura {
            get {
                return ResourceManager.GetString("LabelIdAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string LabelNombreEstudio {
            get {
                return ResourceManager.GetString("LabelNombreEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre para la sub-cuenta periodo.
        /// </summary>
        public static string LabelNombreSubCuentaPeriodo {
            get {
                return ResourceManager.GetString("LabelNombreSubCuentaPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos activos.
        /// </summary>
        public static string LabelPeriodoActivos {
            get {
                return ResourceManager.GetString("LabelPeriodoActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un periodo activo.
        /// </summary>
        public static string LabelSeleccionarPeriodoActivo {
            get {
                return ResourceManager.GetString("LabelSeleccionarPeriodoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignatura.
        /// </summary>
        public static string TextAsignatura {
            get {
                return ResourceManager.GetString("TextAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string TextEstudio {
            get {
                return ResourceManager.GetString("TextEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-cuenta.
        /// </summary>
        public static string TextSubAccount {
            get {
                return ResourceManager.GetString("TextSubAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migración de estudios y asignaturas.
        /// </summary>
        public static string TitleAccount {
            get {
                return ResourceManager.GetString("TitleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de sub-cuenta.
        /// </summary>
        public static string TitleDetalleSubAccount {
            get {
                return ResourceManager.GetString("TitleDetalleSubAccount", resourceCulture);
            }
        }
    }
}
