//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountPeriodoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountPeriodoStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Views.AccountPeriodoStrings", typeof(AccountPeriodoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar cuenta.
        /// </summary>
        public static string BtnDeleteAccount {
            get {
                return ResourceManager.GetString("BtnDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año académico.
        /// </summary>
        public static string LabelAnioAcademico {
            get {
                return ResourceManager.GetString("LabelAnioAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string LabelCodigo {
            get {
                return ResourceManager.GetString("LabelCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string LabelFin {
            get {
                return ResourceManager.GetString("LabelFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin del periodo.
        /// </summary>
        public static string LabelFinPeriodo {
            get {
                return ResourceManager.GetString("LabelFinPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string LabelInicio {
            get {
                return ResourceManager.GetString("LabelInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio del periodo.
        /// </summary>
        public static string LabelInicioPeriodo {
            get {
                return ResourceManager.GetString("LabelInicioPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrar cursos.
        /// </summary>
        public static string LabelMigrarCursos {
            get {
                return ResourceManager.GetString("LabelMigrarCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo de matriculación.
        /// </summary>
        public static string LabelPeriodoMatriculacion {
            get {
                return ResourceManager.GetString("LabelPeriodoMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos no Lectivos.
        /// </summary>
        public static string LabelPeriodoNoLectivo {
            get {
                return ResourceManager.GetString("LabelPeriodoNoLectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIS-ID.
        /// </summary>
        public static string LabelSISID {
            get {
                return ResourceManager.GetString("LabelSISID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar datos.
        /// </summary>
        public static string LabelVerificarDatos {
            get {
                return ResourceManager.GetString("LabelVerificarDatos", resourceCulture);
            }
        }
    }
}
