//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CanvasApiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanvasApiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Services.CanvasApiStrings", typeof(CanvasApiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El account-id proporcionado no se encuentra extendida en la BD.
        /// </summary>
        public static string ErrorAccountError {
            get {
                return ResourceManager.GetString("ErrorAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta solicitada con el ID &apos;{0}&apos;.
        /// </summary>
        public static string ErrorAccountNotExist {
            get {
                return ResourceManager.GetString("ErrorAccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una cuenta de nombre &apos;{0}&apos; asociada al SIS-ID &apos;{1}&apos;.
        /// </summary>
        public static string ErrorAccountSisIDExistente {
            get {
                return ResourceManager.GetString("ErrorAccountSisIDExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al consumir un servicio de canvas consulte con su administrador con el siguiente &lt;strong&gt;codigo: {0}&lt;/strong&gt;.
        /// </summary>
        public static string ErrorApi {
            get {
                return ResourceManager.GetString("ErrorApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignatura {0} no se encuentra asociada previamente a la cuenta con account-id {1}.
        /// </summary>
        public static string ErrorAsignaturaNoAccount {
            get {
                return ResourceManager.GetString("ErrorAsignaturaNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el curso solicitado con el ID &apos;{0}&apos;.
        /// </summary>
        public static string ErrorCourseNotExist {
            get {
                return ResourceManager.GetString("ErrorCourseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El curso {0} ya está asociado con el SIS-ID &apos;{1}&apos;.
        /// </summary>
        public static string ErrorCourseSisIDExistente {
            get {
                return ResourceManager.GetString("ErrorCourseSisIDExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El curso se encuentra publicado, no puede eliminarlo.
        /// </summary>
        public static string ErrorCursoPublicado {
            get {
                return ResourceManager.GetString("ErrorCursoPublicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede modificar el curso ya que se encuentra en estado &apos;Publicado&apos;.
        /// </summary>
        public static string ErrorCursoPublicadoNoModificar {
            get {
                return ResourceManager.GetString("ErrorCursoPublicadoNoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la migración de matrículas.
        /// </summary>
        public static string ErrorEnMigrationMatriculacion {
            get {
                return ResourceManager.GetString("ErrorEnMigrationMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado. Consulte con su administrador con el siguiente &lt;strong&gt;codigo: {0}&lt;/strong&gt;.
        /// </summary>
        public static string ErrorJobServices {
            get {
                return ResourceManager.GetString("ErrorJobServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al realizar la migración de contenido.
        /// </summary>
        public static string ErrorMigrationContent {
            get {
                return ResourceManager.GetString("ErrorMigrationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe ninguna migración con el ID solicitado.
        /// </summary>
        public static string ErrorMigrationNotExists {
            get {
                return ResourceManager.GetString("ErrorMigrationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo nombre de la sub-cuenta periodo es obligatorio.
        /// </summary>
        public static string ErrorNombrePeriodoVacio {
            get {
                return ResourceManager.GetString("ErrorNombrePeriodoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener los resultados de la migración.
        /// </summary>
        public static string ErrorNoResultMigration {
            get {
                return ResourceManager.GetString("ErrorNoResultMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta no tiene un SIS-ID asociado.
        /// </summary>
        public static string ErrorNullSisIdAccount {
            get {
                return ResourceManager.GetString("ErrorNullSisIdAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo estudio es obligatorio.
        /// </summary>
        public static string ErrorParametroEstudioNull {
            get {
                return ResourceManager.GetString("ErrorParametroEstudioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo periodo activo es obligatorio.
        /// </summary>
        public static string ErrorPeriodoActvioNoNull {
            get {
                return ResourceManager.GetString("ErrorPeriodoActvioNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la migración de alumnos.
        /// </summary>
        public static string ErrrorMigrationAlumnos {
            get {
                return ResourceManager.GetString("ErrrorMigrationAlumnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string LinkAssignment {
            get {
                return ResourceManager.GetString("LinkAssignment", resourceCulture);
            }
        }
    }
}
