//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CanvasExtedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanvasExtedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Services.CanvasExtedStrings", typeof(CanvasExtedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta no tiene un SIS-ID definido.
        /// </summary>
        public static string ErrorAccountNoSisId {
            get {
                return ResourceManager.GetString("ErrorAccountNoSisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SIS-ID de la cuenta no es el mismo que el IdEstudio e IdPeriodoMatriculacion con la que se creo.
        /// </summary>
        public static string ErrorAccountPeriodoSisIdCorrupto {
            get {
                return ResourceManager.GetString("ErrorAccountPeriodoSisIdCorrupto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignatura asociada al curso no pertenece a las asignaturas en el Estudio y Periodo de Matriculación de la cuenta seleccionada.
        /// </summary>
        public static string ErrorAsignaturaNoEstudioPeriodoActivo {
            get {
                return ResourceManager.GetString("ErrorAsignaturaNoEstudioPeriodoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las asignaturas sincronizadas inicialmente difieren de las asignaturas del estudio en el Gestor.
        /// </summary>
        public static string ErrorAsignaturasDiferentes {
            get {
                return ResourceManager.GetString("ErrorAsignaturasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignatura asociada al curso en canvas no tiene grupos.
        /// </summary>
        public static string ErrorAsignaturaSinCursos {
            get {
                return ResourceManager.GetString("ErrorAsignaturaSinCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de asignaturas sincronizadas inicialmente es diferente del número de asignaturas del estudio en el Gestor.
        /// </summary>
        public static string ErrorCantidadAsignaturasDiferentes {
            get {
                return ResourceManager.GetString("ErrorCantidadAsignaturasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de periodos activos sincronizados inicialmente es diferente del número de periodos activos del estudio en el Gestor.
        /// </summary>
        public static string ErrorCantidadPeriodoActivosDiferentes {
            get {
                return ResourceManager.GetString("ErrorCantidadPeriodoActivosDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El curso enviado no pertenece a la cuenta.
        /// </summary>
        public static string ErrorCourseNoAccount {
            get {
                return ResourceManager.GetString("ErrorCourseNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El curso no tiene un SIS-ID definido.
        /// </summary>
        public static string ErrorCourseNoSisId {
            get {
                return ResourceManager.GetString("ErrorCourseNoSisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta tiene algún curso sin un SIS-ID definido.
        /// </summary>
        public static string ErrorCourseNotSisId {
            get {
                return ResourceManager.GetString("ErrorCourseNotSisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta tiene algun curso en estado publicado.
        /// </summary>
        public static string ErrorCoursePublish {
            get {
                return ResourceManager.GetString("ErrorCoursePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un curso con un SIS-ID asociado a una asignatura que ya no pertenece al estudio del Gestor.
        /// </summary>
        public static string ErrorCourseSisIdNoAsignatura {
            get {
                return ResourceManager.GetString("ErrorCourseSisIdNoAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El curso &apos;{0}&apos; tiene asociado un SIS-ID que no pertece a las asignaturas del estudio &apos;{1}&apos;.
        /// </summary>
        public static string ErrorCursoConSisIdFaild {
            get {
                return ResourceManager.GetString("ErrorCursoConSisIdFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar la operación ya que existe un curso en estado &apos;Publicado&apos;.
        /// </summary>
        public static string ErrorCursoPublicadoNoMigrate {
            get {
                return ResourceManager.GetString("ErrorCursoPublicadoNoMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar la migración, ya que existe el curso {0} con las fechas no configuradas.
        /// </summary>
        public static string ErrorCursosSinFechaConfigurada {
            get {
                return ResourceManager.GetString("ErrorCursosSinFechaConfigurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SIS-ID asociado a la cuenta no pertenece a un Estudio en el Gestor.
        /// </summary>
        public static string ErrorEstudioNoExiste {
            get {
                return ResourceManager.GetString("ErrorEstudioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas de periodos no lectivos están fuera del rando del inicio y fin del periodo de matriculación.
        /// </summary>
        public static string ErrorFechasNoPeriodoActivo {
            get {
                return ResourceManager.GetString("ErrorFechasNoPeriodoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas están sobre puestas.
        /// </summary>
        public static string ErrorFechasSobrePuestas {
            get {
                return ResourceManager.GetString("ErrorFechasSobrePuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignatura asociada al curso en canvas tiene algún grupo con una fecha de inicio mayor a una fecha de fin definida en el grupo.
        /// </summary>
        public static string ErrorGrupoFechaFinMenorFechaInicio {
            get {
                return ResourceManager.GetString("ErrorGrupoFechaFinMenorFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignatura asociada al curso en canvas tiene algún grupo sin una fecha de fin definida.
        /// </summary>
        public static string ErrorGruposSinFechaFin {
            get {
                return ResourceManager.GetString("ErrorGruposSinFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignatura asociada al curso en canvas tiene algún grupo sin una fecha de inicio definida .
        /// </summary>
        public static string ErrorGruposSinFechaInicio {
            get {
                return ResourceManager.GetString("ErrorGruposSinFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay datos para el estudio y periodo de matriculación solicitados.
        /// </summary>
        public static string ErrorNoAsignaturasWsPorEstudioPeriodoActivo {
            get {
                return ResourceManager.GetString("ErrorNoAsignaturasWsPorEstudioPeriodoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta con ID {0} no cuenta con ningún valor extendido.
        /// </summary>
        public static string ErrorNoExisteAccountExtend {
            get {
                return ResourceManager.GetString("ErrorNoExisteAccountExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El curso con ID {0} no cuenta con ningún valor extendido.
        /// </summary>
        public static string ErrorNoExisteCourseExtend {
            get {
                return ResourceManager.GetString("ErrorNoExisteCourseExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta periodo generado con dicho account-id &apos;{0}&apos;.
        /// </summary>
        public static string ErrorNoExistsAccountPeriodo {
            get {
                return ResourceManager.GetString("ErrorNoExistsAccountPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los periodos activos  sincronizados inicialmente difieren de los periodos activos del estudio en el Gestor.
        /// </summary>
        public static string ErrorPeriodoActivosDiferentes {
            get {
                return ResourceManager.GetString("ErrorPeriodoActivosDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SIS-ID asociado a la cuenta es diferente al estudio asociado inicialmente.
        /// </summary>
        public static string ErrorSisIdAccountCambiado {
            get {
                return ResourceManager.GetString("ErrorSisIdAccountCambiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SIS-ID asociado al curso &apos;{0}&apos; es diferente a la asignatura asociada inicialmente.
        /// </summary>
        public static string ErrorSisIdCourseCambiado {
            get {
                return ResourceManager.GetString("ErrorSisIdCourseCambiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar la eliminación de los cursos de la cuenta {0}.
        /// </summary>
        public static string ErrorTareaDeleteCoursesAccount {
            get {
                return ResourceManager.GetString("ErrorTareaDeleteCoursesAccount", resourceCulture);
            }
        }
    }
}
