//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountExtendStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountExtendStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Scripts.AccountExtendStrings", typeof(AccountExtendStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha inicio debe ser menor a la fecha de fin.
        /// </summary>
        public static string ErrorFechaInicioMayorFin {
            get {
                return ResourceManager.GetString("ErrorFechaInicioMayorFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe alguna fecha con formato incorrecto: &apos;dia/mes/año&apos;.
        /// </summary>
        public static string ErrorFechasIncorrectas {
            get {
                return ResourceManager.GetString("ErrorFechasIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migración de Cursos.
        /// </summary>
        public static string LabelMigracionCursos {
            get {
                return ResourceManager.GetString("LabelMigracionCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado - Migración de Cursos.
        /// </summary>
        public static string LabelResultadoMigracionCursos {
            get {
                return ResourceManager.GetString("LabelResultadoMigracionCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del gestor han sido modificados. ¿Desea sincronizarlos nuevamente?.
        /// </summary>
        public static string MessageDatosModificados {
            get {
                return ResourceManager.GetString("MessageDatosModificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se encuentran correctamente sincronizados.
        /// </summary>
        public static string MessageDatosSincronizados {
            get {
                return ResourceManager.GetString("MessageDatosSincronizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la eliminación de secciones, contenidos, tareas y cursos. Para completar el proceso de eliminación haga click en el siguiente enlace y borre la cuenta.
        /// </summary>
        public static string MessageDeleteAccount {
            get {
                return ResourceManager.GetString("MessageDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de eliminar la cuenta?.
        /// </summary>
        public static string MessageEliminarCuenta {
            get {
                return ResourceManager.GetString("MessageEliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de eliminar el curso?.
        /// </summary>
        public static string MessageEliminarCurso {
            get {
                return ResourceManager.GetString("MessageEliminarCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas fueron validadas correctamente.
        /// </summary>
        public static string MessageFechasNoSobrePuestas {
            get {
                return ResourceManager.GetString("MessageFechasNoSobrePuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas estan sobre puestas.
        /// </summary>
        public static string MessageFechasSobrePuestas {
            get {
                return ResourceManager.GetString("MessageFechasSobrePuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migración realizada {0}.
        /// </summary>
        public static string MessageMigration {
            get {
                return ResourceManager.GetString("MessageMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede generar el periodo. Verifique los datos primero.
        /// </summary>
        public static string MessageNoGenerarPeriodo {
            get {
                return ResourceManager.GetString("MessageNoGenerarPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas están correctamente validadas.
        /// </summary>
        public static string MessagePeriodosNoLectivosCorrectos {
            get {
                return ResourceManager.GetString("MessagePeriodosNoLectivosCorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia: Esta operación recreará los cursos nuevamente eliminando los actuales. ¿Está seguro de realizar la operación?.
        /// </summary>
        public static string MessageSeRecrearanCursos {
            get {
                return ResourceManager.GetString("MessageSeRecrearanCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos en el gestor han cambiado, por favor sincronize los datos primero.
        /// </summary>
        public static string MessageSincronizarPrimero {
            get {
                return ResourceManager.GetString("MessageSincronizarPrimero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalle.
        /// </summary>
        public static string MessageVerDetalle {
            get {
                return ResourceManager.GetString("MessageVerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar periodo.
        /// </summary>
        public static string TitleGenerarPeriodo {
            get {
                return ResourceManager.GetString("TitleGenerarPeriodo", resourceCulture);
            }
        }
    }
}
