//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Scripts.AccountStrings", typeof(AccountStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo estudio es obligatorio.
        /// </summary>
        public static string ErrorParametroEstudioNull {
            get {
                return ResourceManager.GetString("ErrorParametroEstudioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una asignatura.
        /// </summary>
        public static string ErrorSeleccioneAsignatura {
            get {
                return ResourceManager.GetString("ErrorSeleccioneAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un estudio.
        /// </summary>
        public static string ErrorSeleccioneEstudio {
            get {
                return ResourceManager.GetString("ErrorSeleccioneEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta ya tiene asociados cursos con un SIS-ID. Si asocia otro estudio a esta cuenta se borrarán los cursos relacionados..
        /// </summary>
        public static string MessageCambiarSisIdAccount {
            get {
                return ResourceManager.GetString("MessageCambiarSisIdAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar asignatura.
        /// </summary>
        public static string TextAsociarAsignatura {
            get {
                return ResourceManager.GetString("TextAsociarAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar estudio.
        /// </summary>
        public static string TextAsociarEstudio {
            get {
                return ResourceManager.GetString("TextAsociarEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar una asignatura.
        /// </summary>
        public static string TextAsociarUnaAsignatura {
            get {
                return ResourceManager.GetString("TextAsociarUnaAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar un estudio.
        /// </summary>
        public static string TextAsociarUnEstudio {
            get {
                return ResourceManager.GetString("TextAsociarUnEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string TextDetalle {
            get {
                return ResourceManager.GetString("TextDetalle", resourceCulture);
            }
        }
    }
}
