//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MigrationResultStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationResultStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Scripts.MigrationResultStrings", typeof(MigrationResultStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El SIS-ID asociado a este curso no se encuentra en las asignaturas del estudio en su periodo en el gestor.
        /// </summary>
        public static string CodeMessage1 {
            get {
                return ResourceManager.GetString("CodeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de presentación de la tarea, tras el cálculo, no se encuentra en ningún día disponible..
        /// </summary>
        public static string CodeMessage10 {
            get {
                return ResourceManager.GetString("CodeMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de fin de la tarea, tras el cálculo, no se encuentra en ningún día disponible..
        /// </summary>
        public static string CodeMessage11 {
            get {
                return ResourceManager.GetString("CodeMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un grupo en la asignatura del gestor que no tiene una fecha de inicio o fin definida..
        /// </summary>
        public static string CodeMessage2 {
            get {
                return ResourceManager.GetString("CodeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un grupo en la asignatura del gestor con una fecha de inicio mayor a la fecha de fin.
        /// </summary>
        public static string CodeMessage3 {
            get {
                return ResourceManager.GetString("CodeMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante con algún dato personal no definido.
        /// </summary>
        public static string CodeMessage4 {
            get {
                return ResourceManager.GetString("CodeMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante con la contraseña sin el formato correcto de canvas.
        /// </summary>
        public static string CodeMessage5 {
            get {
                return ResourceManager.GetString("CodeMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha inicio de la tarea DEMO esta fuera de rango de la fecha inicio y fin del curso DEMO.
        /// </summary>
        public static string CodeMessage6 {
            get {
                return ResourceManager.GetString("CodeMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de presentación de la tarea DEMO, esta fuera de rango de la fecha de inicio y fin del curso DEMO.
        /// </summary>
        public static string CodeMessage7 {
            get {
                return ResourceManager.GetString("CodeMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha fin de la tarea DEMO esta fuera de rango de la fecha inicio y fin del curso DEMO.
        /// </summary>
        public static string CodeMessage8 {
            get {
                return ResourceManager.GetString("CodeMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio de la tarea, tras el cálculo, no se encuentra en ningún día disponible..
        /// </summary>
        public static string CodeMessage9 {
            get {
                return ResourceManager.GetString("CodeMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin ninguna irregularidad.
        /// </summary>
        public static string MessageSinIrregularidades {
            get {
                return ResourceManager.GetString("MessageSinIrregularidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string TitleCurso {
            get {
                return ResourceManager.GetString("TitleCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante.
        /// </summary>
        public static string TitleEstudiante {
            get {
                return ResourceManager.GetString("TitleEstudiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string TitleTarea {
            get {
                return ResourceManager.GetString("TitleTarea", resourceCulture);
            }
        }
    }
}
