//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Globalization.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScriptTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Globalization.Scripts.ScriptTemplates", typeof(ScriptTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalize.addCultureInfo(&apos;{#CURRENT_CULTURE#}&apos;,{messages:{{#MESSAGES#}}});.
        /// </summary>
        public static string GlobalizationScript {
            get {
                return ResourceManager.GetString("GlobalizationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {#CURRENT_CULTURE#}.
        /// </summary>
        public static string KeyCurrentCulture {
            get {
                return ResourceManager.GetString("KeyCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {#MESSAGES#}.
        /// </summary>
        public static string KeyMessages {
            get {
                return ResourceManager.GetString("KeyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:&quot;{1}&quot;.
        /// </summary>
        public static string KeyValueGlobalizationTemplate {
            get {
                return ResourceManager.GetString("KeyValueGlobalizationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcuenta.
        /// </summary>
        public static string TextSubAccount {
            get {
                return ResourceManager.GetString("TextSubAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurador y migrador de estudios y asignaturas.
        /// </summary>
        public static string TitleAccount {
            get {
                return ResourceManager.GetString("TitleAccount", resourceCulture);
            }
        }
    }
}
