//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIR.Comun.Servicios
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfEstudioDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfEstudioDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioDto[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioDto[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseBase", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioConPeriodosActivosDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.PeriodoDeEstudioConAsignaturas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaConCursos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoConPersonasDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaConCursosCompletosDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoCompletoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioDto))]
    public partial class ServiceResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfEstudioConAsignaturasDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfEstudioConAsignaturasDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioConAsignaturasDto[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioConAsignaturasDto[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfAsignaturaDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfAsignaturaDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaDto[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaDto[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfPersonaDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfPersonaDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfint", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private int RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfEstudioConPeriodosActivosDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfEstudioConPeriodosActivosDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioConPeriodosActivosDto RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.EstudioConPeriodosActivosDto Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfCursoConPersonasDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfCursoConPersonasDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoConPersonasDto[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoConPersonasDto[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfAsignaturaConCursosCompletosDtoWP8jzdkm", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfAsignaturaConCursosCompletosDtoWP8jzdkm : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaConCursosCompletosDto[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaConCursosCompletosDto[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfintuHEDJ7Dj", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Comun.Servicios")]
    public partial class RespuestaServicioOfArrayOfintuHEDJ7Dj : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodigoField;
        
        private string ErrorDescripcionDesarrolloField;
        
        private string ErrorDescripcionInterfazField;
        
        private bool EsErrorField;
        
        private int[] RespuestaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCodigo
        {
            get
            {
                return this.ErrorCodigoField;
            }
            set
            {
                this.ErrorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionDesarrollo
        {
            get
            {
                return this.ErrorDescripcionDesarrolloField;
            }
            set
            {
                this.ErrorDescripcionDesarrolloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescripcionInterfaz
        {
            get
            {
                return this.ErrorDescripcionInterfazField;
            }
            set
            {
                this.ErrorDescripcionInterfazField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError
        {
            get
            {
                return this.EsErrorField;
            }
            set
            {
                this.EsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Respuesta
        {
            get
            {
                return this.RespuestaField;
            }
            set
            {
                this.RespuestaField = value;
            }
        }
    }
}
namespace UNIR.Servicios.Integracion.Negocio.ClasesDto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudioDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class EstudioDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private int idEstudioField;
        
        private string sNombreEstudioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudio
        {
            get
            {
                return this.idEstudioField;
            }
            set
            {
                this.idEstudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreEstudio
        {
            get
            {
                return this.sNombreEstudioField;
            }
            set
            {
                this.sNombreEstudioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsignaturaDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class AsignaturaDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private int iCursoAsignaturaField;
        
        private int idAsignaturaField;
        
        private string sNombreAsignaturaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCursoAsignatura
        {
            get
            {
                return this.iCursoAsignaturaField;
            }
            set
            {
                this.iCursoAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAsignatura
        {
            get
            {
                return this.idAsignaturaField;
            }
            set
            {
                this.idAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreAsignatura
        {
            get
            {
                return this.sNombreAsignaturaField;
            }
            set
            {
                this.sNombreAsignaturaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class PersonaDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private string correoElectronicoField;
        
        private int idPersonaField;
        
        private int idTipoPersonaField;
        
        private string loginField;
        
        private string passwordField;
        
        private string sApellidosPersonaField;
        
        private string sNIFField;
        
        private string sNombrePersonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoPersona
        {
            get
            {
                return this.idTipoPersonaField;
            }
            set
            {
                this.idTipoPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sApellidosPersona
        {
            get
            {
                return this.sApellidosPersonaField;
            }
            set
            {
                this.sApellidosPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNIF
        {
            get
            {
                return this.sNIFField;
            }
            set
            {
                this.sNIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombrePersona
        {
            get
            {
                return this.sNombrePersonaField;
            }
            set
            {
                this.sNombrePersonaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudioConPeriodosActivosDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class EstudioConPeriodosActivosDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private int idEstudioField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.PeriodoDeEstudioConAsignaturas[] listaPeriodosActivosField;
        
        private string sNombreEstudioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudio
        {
            get
            {
                return this.idEstudioField;
            }
            set
            {
                this.idEstudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.PeriodoDeEstudioConAsignaturas[] listaPeriodosActivos
        {
            get
            {
                return this.listaPeriodosActivosField;
            }
            set
            {
                this.listaPeriodosActivosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreEstudio
        {
            get
            {
                return this.sNombreEstudioField;
            }
            set
            {
                this.sNombreEstudioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoDeEstudioConAsignaturas", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class PeriodoDeEstudioConAsignaturas : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private System.DateTime fechaFinExamenesQ1Field;
        
        private System.DateTime fechaFinExamenesQ2Field;
        
        private System.DateTime fechaFinExtraordinariaField;
        
        private System.DateTime fechaFinPeriodoField;
        
        private System.DateTime fechaFinQ1Field;
        
        private System.DateTime fechaFinQ2Field;
        
        private System.DateTime fechaInicioExamenesQ1Field;
        
        private System.DateTime fechaInicioExamenesQ2Field;
        
        private System.DateTime fechaInicioExtraordinariaField;
        
        private System.DateTime fechaInicioPeriodoField;
        
        private System.DateTime fechaInicioQ1Field;
        
        private System.DateTime fechaInicioQ2Field;
        
        private System.DateTime fechaInicioSemana0Field;
        
        private System.Nullable<int> iNumPeriodoField;
        
        private int idPeriodoMatriculacionField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaConCursos[] listaAsignaturasField;
        
        private string sAyoAcademincoField;
        
        private string sNombrePeriodoMatriculacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFinExamenesQ1
        {
            get
            {
                return this.fechaFinExamenesQ1Field;
            }
            set
            {
                this.fechaFinExamenesQ1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFinExamenesQ2
        {
            get
            {
                return this.fechaFinExamenesQ2Field;
            }
            set
            {
                this.fechaFinExamenesQ2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFinExtraordinaria
        {
            get
            {
                return this.fechaFinExtraordinariaField;
            }
            set
            {
                this.fechaFinExtraordinariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFinPeriodo
        {
            get
            {
                return this.fechaFinPeriodoField;
            }
            set
            {
                this.fechaFinPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFinQ1
        {
            get
            {
                return this.fechaFinQ1Field;
            }
            set
            {
                this.fechaFinQ1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaFinQ2
        {
            get
            {
                return this.fechaFinQ2Field;
            }
            set
            {
                this.fechaFinQ2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioExamenesQ1
        {
            get
            {
                return this.fechaInicioExamenesQ1Field;
            }
            set
            {
                this.fechaInicioExamenesQ1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioExamenesQ2
        {
            get
            {
                return this.fechaInicioExamenesQ2Field;
            }
            set
            {
                this.fechaInicioExamenesQ2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioExtraordinaria
        {
            get
            {
                return this.fechaInicioExtraordinariaField;
            }
            set
            {
                this.fechaInicioExtraordinariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioPeriodo
        {
            get
            {
                return this.fechaInicioPeriodoField;
            }
            set
            {
                this.fechaInicioPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioQ1
        {
            get
            {
                return this.fechaInicioQ1Field;
            }
            set
            {
                this.fechaInicioQ1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioQ2
        {
            get
            {
                return this.fechaInicioQ2Field;
            }
            set
            {
                this.fechaInicioQ2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInicioSemana0
        {
            get
            {
                return this.fechaInicioSemana0Field;
            }
            set
            {
                this.fechaInicioSemana0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> iNumPeriodo
        {
            get
            {
                return this.iNumPeriodoField;
            }
            set
            {
                this.iNumPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodoMatriculacion
        {
            get
            {
                return this.idPeriodoMatriculacionField;
            }
            set
            {
                this.idPeriodoMatriculacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaConCursos[] listaAsignaturas
        {
            get
            {
                return this.listaAsignaturasField;
            }
            set
            {
                this.listaAsignaturasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAyoAcademinco
        {
            get
            {
                return this.sAyoAcademincoField;
            }
            set
            {
                this.sAyoAcademincoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombrePeriodoMatriculacion
        {
            get
            {
                return this.sNombrePeriodoMatriculacionField;
            }
            set
            {
                this.sNombrePeriodoMatriculacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsignaturaConCursos", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class AsignaturaConCursos : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private int iNumeroAnyoCursoField;
        
        private int idAsignaturaField;
        
        private System.Nullable<int> idPlantillaAsignaturaField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoDto[] listaCursosField;
        
        private int numeroECTSField;
        
        private string sCaracterAsignaturaField;
        
        private string sDenominacionAsignaturaField;
        
        private string sPeriodoLectivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iNumeroAnyoCurso
        {
            get
            {
                return this.iNumeroAnyoCursoField;
            }
            set
            {
                this.iNumeroAnyoCursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAsignatura
        {
            get
            {
                return this.idAsignaturaField;
            }
            set
            {
                this.idAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPlantillaAsignatura
        {
            get
            {
                return this.idPlantillaAsignaturaField;
            }
            set
            {
                this.idPlantillaAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoDto[] listaCursos
        {
            get
            {
                return this.listaCursosField;
            }
            set
            {
                this.listaCursosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroECTS
        {
            get
            {
                return this.numeroECTSField;
            }
            set
            {
                this.numeroECTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCaracterAsignatura
        {
            get
            {
                return this.sCaracterAsignaturaField;
            }
            set
            {
                this.sCaracterAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDenominacionAsignatura
        {
            get
            {
                return this.sDenominacionAsignaturaField;
            }
            set
            {
                this.sDenominacionAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sPeriodoLectivo
        {
            get
            {
                return this.sPeriodoLectivoField;
            }
            set
            {
                this.sPeriodoLectivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class CursoDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private System.Nullable<System.DateTime> fechaFinCursoField;
        
        private System.Nullable<System.DateTime> fechaInicioCursoField;
        
        private System.Nullable<int> iNumeroGrupoRealField;
        
        private int idCursoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaFinCurso
        {
            get
            {
                return this.fechaFinCursoField;
            }
            set
            {
                this.fechaFinCursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaInicioCurso
        {
            get
            {
                return this.fechaInicioCursoField;
            }
            set
            {
                this.fechaInicioCursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> iNumeroGrupoReal
        {
            get
            {
                return this.iNumeroGrupoRealField;
            }
            set
            {
                this.iNumeroGrupoRealField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCurso
        {
            get
            {
                return this.idCursoField;
            }
            set
            {
                this.idCursoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoConPersonasDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class CursoConPersonasDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto[] ListaPersonasField;
        
        private int idCursoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto[] ListaPersonas
        {
            get
            {
                return this.ListaPersonasField;
            }
            set
            {
                this.ListaPersonasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCurso
        {
            get
            {
                return this.idCursoField;
            }
            set
            {
                this.idCursoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsignaturaConCursosCompletosDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class AsignaturaConCursosCompletosDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private int iNumeroAnyoCursoField;
        
        private int idAsignaturaField;
        
        private System.Nullable<int> idPlantillaAsignaturaField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoCompletoDto[] listaCursosField;
        
        private int numeroECTSField;
        
        private string sCaracterAsignaturaField;
        
        private string sDenominacionAsignaturaField;
        
        private string sPeriodoLectivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iNumeroAnyoCurso
        {
            get
            {
                return this.iNumeroAnyoCursoField;
            }
            set
            {
                this.iNumeroAnyoCursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAsignatura
        {
            get
            {
                return this.idAsignaturaField;
            }
            set
            {
                this.idAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPlantillaAsignatura
        {
            get
            {
                return this.idPlantillaAsignaturaField;
            }
            set
            {
                this.idPlantillaAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.CursoCompletoDto[] listaCursos
        {
            get
            {
                return this.listaCursosField;
            }
            set
            {
                this.listaCursosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroECTS
        {
            get
            {
                return this.numeroECTSField;
            }
            set
            {
                this.numeroECTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCaracterAsignatura
        {
            get
            {
                return this.sCaracterAsignaturaField;
            }
            set
            {
                this.sCaracterAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDenominacionAsignatura
        {
            get
            {
                return this.sDenominacionAsignaturaField;
            }
            set
            {
                this.sDenominacionAsignaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sPeriodoLectivo
        {
            get
            {
                return this.sPeriodoLectivoField;
            }
            set
            {
                this.sPeriodoLectivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoCompletoDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class CursoCompletoDto : UNIR.Comun.Servicios.ServiceResponseBase
    {
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto[] ListaPersonasField;
        
        private System.Nullable<System.DateTime> fechaFinCursoField;
        
        private System.Nullable<System.DateTime> fechaInicioCursoField;
        
        private System.Nullable<int> iNumeroGrupoRealField;
        
        private int idCursoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.PersonaDto[] ListaPersonas
        {
            get
            {
                return this.ListaPersonasField;
            }
            set
            {
                this.ListaPersonasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaFinCurso
        {
            get
            {
                return this.fechaFinCursoField;
            }
            set
            {
                this.fechaFinCursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaInicioCurso
        {
            get
            {
                return this.fechaInicioCursoField;
            }
            set
            {
                this.fechaInicioCursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> iNumeroGrupoReal
        {
            get
            {
                return this.iNumeroGrupoRealField;
            }
            set
            {
                this.iNumeroGrupoRealField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCurso
        {
            get
            {
                return this.idCursoField;
            }
            set
            {
                this.idCursoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudioConAsignaturasDto", Namespace="http://schemas.datacontract.org/2004/07/UNIR.Servicios.Integracion.Negocio.Clases" +
        "Dto")]
    public partial class EstudioConAsignaturasDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idEstudioField;
        
        private UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaDto[] listaAsignaturasField;
        
        private string sNombreEstudioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudio
        {
            get
            {
                return this.idEstudioField;
            }
            set
            {
                this.idEstudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNIR.Servicios.Integracion.Negocio.ClasesDto.AsignaturaDto[] listaAsignaturas
        {
            get
            {
                return this.listaAsignaturasField;
            }
            set
            {
                this.listaAsignaturasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreEstudio
        {
            get
            {
                return this.sNombreEstudioField;
            }
            set
            {
                this.sNombreEstudioField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEstudios")]
public interface IEstudios
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerEstudiosUNIR", ReplyAction="http://tempuri.org/IEstudios/ObtenerEstudiosUNIRResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioDtoWP8jzdkm ObtenerEstudiosUNIR(int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerEstudiosUNIR", ReplyAction="http://tempuri.org/IEstudios/ObtenerEstudiosUNIRResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioDtoWP8jzdkm> ObtenerEstudiosUNIRAsync(int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerEstudiosUNIRConAsignaturas", ReplyAction="http://tempuri.org/IEstudios/ObtenerEstudiosUNIRConAsignaturasResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioConAsignaturasDtoWP8jzdkm ObtenerEstudiosUNIRConAsignaturas(int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerEstudiosUNIRConAsignaturas", ReplyAction="http://tempuri.org/IEstudios/ObtenerEstudiosUNIRConAsignaturasResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioConAsignaturasDtoWP8jzdkm> ObtenerEstudiosUNIRConAsignaturasAsync(int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerAsignaturasDeEstudio", ReplyAction="http://tempuri.org/IEstudios/ObtenerAsignaturasDeEstudioResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaDtoWP8jzdkm ObtenerAsignaturasDeEstudio(int idEstudio);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerAsignaturasDeEstudio", ReplyAction="http://tempuri.org/IEstudios/ObtenerAsignaturasDeEstudioResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaDtoWP8jzdkm> ObtenerAsignaturasDeEstudioAsync(int idEstudio);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerAlumnosDeAsginatura", ReplyAction="http://tempuri.org/IEstudios/ObtenerAlumnosDeAsginaturaResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfPersonaDtoWP8jzdkm ObtenerAlumnosDeAsginatura(int idEstudio, int idAsignatura, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerAlumnosDeAsginatura", ReplyAction="http://tempuri.org/IEstudios/ObtenerAlumnosDeAsginaturaResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfPersonaDtoWP8jzdkm> ObtenerAlumnosDeAsginaturaAsync(int idEstudio, int idAsignatura, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerIDAsignaturaDeCurso", ReplyAction="http://tempuri.org/IEstudios/ObtenerIDAsignaturaDeCursoResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfint ObtenerIDAsignaturaDeCurso(int idCurso);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerIDAsignaturaDeCurso", ReplyAction="http://tempuri.org/IEstudios/ObtenerIDAsignaturaDeCursoResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfint> ObtenerIDAsignaturaDeCursoAsync(int idCurso);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerIdCursoDeAsignaturaAlumno", ReplyAction="http://tempuri.org/IEstudios/ObtenerIdCursoDeAsignaturaAlumnoResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfint ObtenerIdCursoDeAsignaturaAlumno(int idPeriodoMatriculacion, int idAlumno, int idEstudio, int idAsignatura);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerIdCursoDeAsignaturaAlumno", ReplyAction="http://tempuri.org/IEstudios/ObtenerIdCursoDeAsignaturaAlumnoResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfint> ObtenerIdCursoDeAsignaturaAlumnoAsync(int idPeriodoMatriculacion, int idAlumno, int idEstudio, int idAsignatura);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerCursosDeAsignaturasDeEstudio", ReplyAction="http://tempuri.org/IEstudios/ObtenerCursosDeAsignaturasDeEstudioResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfEstudioConPeriodosActivosDtoWP8jzdkm ObtenerCursosDeAsignaturasDeEstudio(int idEstudio);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerCursosDeAsignaturasDeEstudio", ReplyAction="http://tempuri.org/IEstudios/ObtenerCursosDeAsignaturasDeEstudioResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfEstudioConPeriodosActivosDtoWP8jzdkm> ObtenerCursosDeAsignaturasDeEstudioAsync(int idEstudio);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerPersonasDeCursosDeAsignatura", ReplyAction="http://tempuri.org/IEstudios/ObtenerPersonasDeCursosDeAsignaturaResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfCursoConPersonasDtoWP8jzdkm ObtenerPersonasDeCursosDeAsignatura(int idEstudio, int idAsignatura, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerPersonasDeCursosDeAsignatura", ReplyAction="http://tempuri.org/IEstudios/ObtenerPersonasDeCursosDeAsignaturaResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfCursoConPersonasDtoWP8jzdkm> ObtenerPersonasDeCursosDeAsignaturaAsync(int idEstudio, int idAsignatura, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerGruposConPersonasPorAsignatura", ReplyAction="http://tempuri.org/IEstudios/ObtenerGruposConPersonasPorAsignaturaResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaConCursosCompletosDtoWP8jzdkm ObtenerGruposConPersonasPorAsignatura(int idEstudio, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObtenerGruposConPersonasPorAsignatura", ReplyAction="http://tempuri.org/IEstudios/ObtenerGruposConPersonasPorAsignaturaResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaConCursosCompletosDtoWP8jzdkm> ObtenerGruposConPersonasPorAsignaturaAsync(int idEstudio, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObteneridCursosDeEstudio", ReplyAction="http://tempuri.org/IEstudios/ObteneridCursosDeEstudioResponse")]
    UNIR.Comun.Servicios.RespuestaServicioOfArrayOfintuHEDJ7Dj ObteneridCursosDeEstudio(int idEstudio, int idPeridoMatriculacion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudios/ObteneridCursosDeEstudio", ReplyAction="http://tempuri.org/IEstudios/ObteneridCursosDeEstudioResponse")]
    System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfintuHEDJ7Dj> ObteneridCursosDeEstudioAsync(int idEstudio, int idPeridoMatriculacion);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEstudiosChannel : IEstudios, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EstudiosClient : System.ServiceModel.ClientBase<IEstudios>, IEstudios
{
    
    public EstudiosClient()
    {
    }
    
    public EstudiosClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EstudiosClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EstudiosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EstudiosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioDtoWP8jzdkm ObtenerEstudiosUNIR(int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerEstudiosUNIR(idPeridoMatriculacion);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioDtoWP8jzdkm> ObtenerEstudiosUNIRAsync(int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerEstudiosUNIRAsync(idPeridoMatriculacion);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioConAsignaturasDtoWP8jzdkm ObtenerEstudiosUNIRConAsignaturas(int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerEstudiosUNIRConAsignaturas(idPeridoMatriculacion);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfEstudioConAsignaturasDtoWP8jzdkm> ObtenerEstudiosUNIRConAsignaturasAsync(int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerEstudiosUNIRConAsignaturasAsync(idPeridoMatriculacion);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaDtoWP8jzdkm ObtenerAsignaturasDeEstudio(int idEstudio)
    {
        return base.Channel.ObtenerAsignaturasDeEstudio(idEstudio);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaDtoWP8jzdkm> ObtenerAsignaturasDeEstudioAsync(int idEstudio)
    {
        return base.Channel.ObtenerAsignaturasDeEstudioAsync(idEstudio);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfPersonaDtoWP8jzdkm ObtenerAlumnosDeAsginatura(int idEstudio, int idAsignatura, int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerAlumnosDeAsginatura(idEstudio, idAsignatura, idPeridoMatriculacion);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfPersonaDtoWP8jzdkm> ObtenerAlumnosDeAsginaturaAsync(int idEstudio, int idAsignatura, int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerAlumnosDeAsginaturaAsync(idEstudio, idAsignatura, idPeridoMatriculacion);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfint ObtenerIDAsignaturaDeCurso(int idCurso)
    {
        return base.Channel.ObtenerIDAsignaturaDeCurso(idCurso);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfint> ObtenerIDAsignaturaDeCursoAsync(int idCurso)
    {
        return base.Channel.ObtenerIDAsignaturaDeCursoAsync(idCurso);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfint ObtenerIdCursoDeAsignaturaAlumno(int idPeriodoMatriculacion, int idAlumno, int idEstudio, int idAsignatura)
    {
        return base.Channel.ObtenerIdCursoDeAsignaturaAlumno(idPeriodoMatriculacion, idAlumno, idEstudio, idAsignatura);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfint> ObtenerIdCursoDeAsignaturaAlumnoAsync(int idPeriodoMatriculacion, int idAlumno, int idEstudio, int idAsignatura)
    {
        return base.Channel.ObtenerIdCursoDeAsignaturaAlumnoAsync(idPeriodoMatriculacion, idAlumno, idEstudio, idAsignatura);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfEstudioConPeriodosActivosDtoWP8jzdkm ObtenerCursosDeAsignaturasDeEstudio(int idEstudio)
    {
        return base.Channel.ObtenerCursosDeAsignaturasDeEstudio(idEstudio);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfEstudioConPeriodosActivosDtoWP8jzdkm> ObtenerCursosDeAsignaturasDeEstudioAsync(int idEstudio)
    {
        return base.Channel.ObtenerCursosDeAsignaturasDeEstudioAsync(idEstudio);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfCursoConPersonasDtoWP8jzdkm ObtenerPersonasDeCursosDeAsignatura(int idEstudio, int idAsignatura, int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerPersonasDeCursosDeAsignatura(idEstudio, idAsignatura, idPeridoMatriculacion);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfCursoConPersonasDtoWP8jzdkm> ObtenerPersonasDeCursosDeAsignaturaAsync(int idEstudio, int idAsignatura, int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerPersonasDeCursosDeAsignaturaAsync(idEstudio, idAsignatura, idPeridoMatriculacion);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaConCursosCompletosDtoWP8jzdkm ObtenerGruposConPersonasPorAsignatura(int idEstudio, int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerGruposConPersonasPorAsignatura(idEstudio, idPeridoMatriculacion);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfAsignaturaConCursosCompletosDtoWP8jzdkm> ObtenerGruposConPersonasPorAsignaturaAsync(int idEstudio, int idPeridoMatriculacion)
    {
        return base.Channel.ObtenerGruposConPersonasPorAsignaturaAsync(idEstudio, idPeridoMatriculacion);
    }
    
    public UNIR.Comun.Servicios.RespuestaServicioOfArrayOfintuHEDJ7Dj ObteneridCursosDeEstudio(int idEstudio, int idPeridoMatriculacion)
    {
        return base.Channel.ObteneridCursosDeEstudio(idEstudio, idPeridoMatriculacion);
    }
    
    public System.Threading.Tasks.Task<UNIR.Comun.Servicios.RespuestaServicioOfArrayOfintuHEDJ7Dj> ObteneridCursosDeEstudioAsync(int idEstudio, int idPeridoMatriculacion)
    {
        return base.Channel.ObteneridCursosDeEstudioAsync(idEstudio, idPeridoMatriculacion);
    }
}
