// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_table_accountgenerates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_table_accountgenerates));
        
        string IMigrationMetadata.Id
        {
            get { return "201705291314054_add_table_accountgenerates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
